version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  malware.cyrhades.fr:
    image: anssi/fcsc2021-forensics-malware:latest
    ports:
      - ${PORT_SSH}:4000
